[package]
name = "enigma"
version = "0.1.0"
authors = ["Bla≈æ Hrastnik <blaz@mxxn.io>"]
license = "MPL-2.0"
edition = "2018"

[badges]
travis-ci = { repository = "archseer/enigma" }
appveyor = { repository = "archseer/enigma" }

[lib]
name = "libenigma"
doctest = false

[[bin]]
name = "enigma"
test = false

[dependencies]
nom = "4.1.1"
num = "0.2.0"
libflate = "0.1"
once_cell = "0.1.6"
parking_lot = "0.7.0"
allocator_api = "0.5.0"
time = "0.1.40"
chrono = "0.4.6"
bitflags = "1.0.4"
getopts = "0.2.18"
hamt-rs = { git = "https://github.com/archseer/hamt-rs/", branch = "remove-reqs" }
log = "0.4"
hashbrown = "0.1.7"
nodrop = "0.1.13"
statrs = "0.10.0"

[dev-dependencies]
quickcheck = "0.8.0"

# [profile.release]
# debug = true
